[package]
name = "game_of_life"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo-timers = "0.3.0"
getrandom = { version = "0.3", features = ["wasm_js"] }
rand = "0.9"
log = "0.4.29"
spair = { path = "../../spair" }
