[package]
name = "todomvc2"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
spair = { path = "../../spair", package = "spair2" }
serde = { version = "1.0", features = ["derive"] }
gloo-storage = "0.3"
wasm-logger = "0.2"
log = "0.4"
